name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check required secrets
        run: |
          missing=false

          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "Warning: Secret SSH_PRIVATE_KEY is missing!"
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Add to known hosts
        if: env.skip != 'true'
        run: |
          mkdir -p ~/.ssh/known_hosts
          cp known_hosts ~/.ssh/known_hosts

      - name: SSH
        if: env.skip != 'true'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd selection-portal
            git stash
            git pull origin main

            source ~/.profile
            source ~/.nvm/nvm.sh
            nvm use v20.9.0

            cd server
            npm install
            npx prisma migrate deploy
            npx prisma generate
            npx tsc -b
            pm2 restart winnners-selection-portal-backend
            cd ../client
            npm install --legacy-peer-deps
            npm run build
            pm2 restart winnners-selection-portal-frontend
